### ISSUE TITLE
Deploying guide might have some error.

### ISSUE THREAD

**Issue by fscnick** [skycomic-org/dockerfile-skycomic#1]
I tried to run this docker and encountered some error.

1. The first line of Dockerfile ```[ensky] ~ > sc``` might need be comment out. I am not sure what it does, just commenting it out. Then, it start to continue.

2. The fifth instruction of README.md ```docker run --name skycomic.org -p 8080:80 -d skycomic``` might need be changed to ```docker run --name skycomic.org -p 8080:80 -d skycomic.org```.

3. The last instruction of README.md will produce an error about ```/usr/local/bin/php: not found```. Thus, I create a symbolic link to ```/usr/bin/php```

These fixes merely go through the building step, but I am not sure it would produce another issue in the future or not.

**Comment by ensky** [comment]
how about send a pull request to us ;D
